### ISSUE TITLE
AstroChart - React Native

### ISSUE THREAD

**Issue by debolhas** [afucher/afucher#1]
Olá, tudo bem? Meu nome é Webert.

Notei que vc é um colaborador ativo do da biblioteca https://github.com/Kibo/AstroChart

Estou estudando React Native a pouco tempo, e gostaria de usar essa biblioteca. Saberia dizer quais modificações seriam necessárias para conseguir utilizá-la no React Native ?

Pesquisando, encontrei esta dica: https://stackoverflow.com/questions/52743387/convert-svg-to-react-native-svg/53452465

De qualquer forma, agradeço pela atenção

**Comment by afucher** [comment]
Opa, acabou que conversamos por e-mail :)

Qlqr coisa, só falar ✉️
